name: Deploy workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_IMAGE_NAME: product-service
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      EC2_PUBLIC_IP_ADDRESS: ${{ secrets.EC2_PUBLIC_IP_ADDRESS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Generate Build Number
        run: |
          BUILD_NUMBER=$(date +'%d%m%Y%H%M%S')
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
          echo "Generated Build Number: $BUILD_NUMBER"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      - name: Maven Clean Verify
        run: mvn -B -ntp clean verify jib:build -Ddocker.image.tag=$BUILD_NUMBER
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ env.EC2_SSH_PRIVATE_KEY }}
      - name: SSH to EC2 and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_IP_ADDRESS << EOF
            sudo -i
            cd ~
            sed -i 's|image: '"$DOCKER_USERNAME"'/'"$DOCKER_IMAGE_NAME"':.*$|image: '"$DOCKER_USERNAME"'/'"$DOCKER_IMAGE_NAME"':'"$BUILD_NUMBER"'|' docker-compose.yml
            docker-compose pull
            docker-compose up -d product-service
            docker image prune -f
            docker ps
            echo "$BUILD_NUMBER" > build-number.txt
          EOF